name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - name: npm install vuepress
    #   run: |
    #     npm install -g vuepress
    # - name: npm install, build, and test
    #   run: |
    #     npm run build --if-present
    -
      name: Build
      run: |
        mkdir public
        cat > public/index.html <<EOL
        <!doctype html>
        <html>
          <head>
            <title>GitHub Pages deployed!</title>
          </head>
          <body>
            <p>GitHub Pages with <strong>${{ github.sha }}</strong> commit ID has been deployed through <a href="https://github.com/marketplace/actions/github-pages">GitHub Pages action</a> successfully.</p>
          </body>
        </html>
        EOL
    - name: GitHub Pages Deploy
      # uses: maxheld83/ghpages@v0.1.2
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
